source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
pod 'JSQMessagesViewController'
pod 'googleplus-ios-sdk', '~> 1.7.1'
pod 'SCLAlertView-Objective-C'
pod 'EDStarRating'
